SMILETRACK:
  # BoTSORT
  track_high_thresh: 0.5          # tracking confidence threshold
  track_low_thresh: 0.1           # lowest detection threshold
  new_track_thresh: 0.6           # new track thresh
  track_buffer: 30                # the frames for keep lost tracks
  match_thresh: 0.8               # matching threshold for tracking
  aspect_ratio_thresh: 1.6        # threshold for filtering out boxes of which aspect ratio are above the given value.
  min_box_area: 10                # filter out tiny boxes
  mot20: False               # fuse score and iou for association

  # CMC
  cmc_method: "file"              # cmc method: files (Vidstab GMC) | sparseOptFlow |orb | ecc
  ablation: False                 # ablation

  # ReID
  with_reid: False                                          # with ReID module.
  fast_reid_config: "fast_reid/configs/MOT17/sbs_S50.yml"   # reid config file path
  fast_reid_weights: "pretrained/mot17_sbs_S50.pth"         # reid config file path
  proximity_thresh': 0.5                                    # threshold for rejecting low overlap reid matches
  appearance_thresh: 0.25                                   # threshold for rejecting low appearance similarity reid matches